version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3

  botnetjobs.api:
    image: ${DOCKER_REGISTRY-}botnetjobsapi
    environment:
      rabbitmq__Hostname: rabbitmq
    build:
      context: .
      dockerfile: Services/BotnetJobs/BotnetJobs.API/Dockerfile
    depends_on:
      - rabbitmq

  bots.api:
    image: ${DOCKER_REGISTRY-}botsapi
    environment:
      rabbitmq__Hostname: rabbitmq
    build:
      context: .
      dockerfile: Services/Bots/Bots.API/Dockerfile
    depends_on:
      - rabbitmq
  
  botnetwapp:
    container_name: botnetwapp
    build:
      context: .
      dockerfile: BotnetWebApp/botnetwebapp/Dockerfile
    stdin_open: true
    ports:
      - 3001:3000
    volumes:
      - './BotnetWebApp/botnetwebapp:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true
    environment:
      REACT_APP_BOTSAPI: bots.api
      REACT_APP_BOTNETJOBSAPI: botnetjobs.api
    depends_on:
      - botnetjobs.api
      - bots.api
